theme: jekyll-theme-minimal
title: Branson Abira
logo: WhatsApp Image 2026-02-20 at 16.06.37.jpeg
description: IT Professional & Aspiring Cybersecurity Analyst 🔐
plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
